version: "3.8"

services:
  org_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: org_service
    command: uvicorn org_service.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_OAUTH_REDIRECT_URI=${GOOGLE_OAUTH_REDIRECT_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRY_SECONDS=${JWT_EXPIRY_SECONDS:-604800}
      - HARDCODED_ORG_ID=${HARDCODED_ORG_ID:-11111111-1111-1111-1111-111111111111}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
