apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: org-service
  labels:
    app: org-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: org-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
